// Student Database
const students = [
  {
    rollNumber: "TEC001",
    name: "Arjun Kumar",
    course: "Web Development Fundamentals",
    courseCode: "WD101",
    feeStatus: "Paid",
    admissionDate: "2023-01-15",
    contactNumber: "+1 (123) 456-7890",
    email: "arjun.kumar@example.com",
    courseDetails: {
      instructor: "Prof. Aravind Raj",
      duration: "12 Weeks",
      schedule: "Mon, Wed, Fri (10:00 AM - 12:00 PM)",
      completionStatus: "In Progress (75% completed)",
      nextExamDate: "2023-05-20",
    },
  },
  {
    rollNumber: "TEC002",
    name: "Lakshmi Priya",
    course: "Data Science & Analytics",
    courseCode: "DS201",
    feeStatus: "Pending",
    admissionDate: "2023-02-10",
    contactNumber: "+1 (234) 567-8901",
    email: "lakshmi.priya@example.com",
    courseDetails: {
      instructor: "Dr. Kavitha Devi",
      duration: "16 Weeks",
      schedule: "Tue, Thu (2:00 PM - 5:00 PM)",
      completionStatus: "In Progress (50% completed)",
      nextExamDate: "2023-06-15",
    },
  },
  {
    rollNumber: "TEC003",
    name: "Prakash Kumar",
    course: "Cybersecurity",
    courseCode: "CS301",
    feeStatus: "Overdue",
    admissionDate: "2023-01-05",
    contactNumber: "+1 (345) 678-9012",
    email: "prakash.kumar@example.com",
    courseDetails: {
      instructor: "Senthil Kumar",
      duration: "14 Weeks",
      schedule: "Mon, Wed, Fri (2:00 PM - 4:00 PM)",
      completionStatus: "In Progress (30% completed)",
      nextExamDate: "2023-05-25",
    },
  },
  {
    rollNumber: "TEC004",
    name: "Meena Lakshmi",
    course: "Mobile App Development",
    courseCode: "MD201",
    feeStatus: "Paid",
    admissionDate: "2023-03-01",
    contactNumber: "+1 (456) 789-0123",
    email: "meena.lakshmi@example.com",
    courseDetails: {
      instructor: "Anitha Ramesh",
      duration: "15 Weeks",
      schedule: "Tue, Thu (10:00 AM - 1:00 PM)",
      completionStatus: "In Progress (25% completed)",
      nextExamDate: "2023-06-10",
    },
  },
  {
    rollNumber: "TEC005",
    name: "Saravanan Gopal",
    course: "Python Programming",
    courseCode: "PY101",
    feeStatus: "Paid",
    admissionDate: "2023-02-20",
    contactNumber: "+1 (567) 890-1234",
    email: "saravanan.gopal@example.com",
    courseDetails: {
      instructor: "Dr. Deepak Kumar",
      duration: "10 Weeks",
      schedule: "Mon, Wed (6:00 PM - 8:00 PM)",
      completionStatus: "In Progress (60% completed)",
      nextExamDate: "2023-05-15",
    },
  },
]

// Course Database
const courses = {
  "web-dev-101": {
    title: "Web Development Fundamentals",
    code: "WD101",
    description:
      "A comprehensive introduction to web development covering HTML, CSS, JavaScript, and responsive design principles. Students will learn to build modern, responsive websites from scratch.",
    instructor: "Prof. Aravind Raj",
    duration: "12 Weeks",
    level: "Beginner",
    fee: "$499",
    schedule: "Mon, Wed, Fri (10:00 AM - 12:00 PM)",
    prerequisites: "None",
    syllabus: [
      "Week 1-2: HTML Fundamentals",
      "Week 3-4: CSS Styling and Layout",
      "Week 5-6: JavaScript Basics",
      "Week 7-8: DOM Manipulation",
      "Week 9-10: Responsive Design",
      "Week 11-12: Final Project Development",
    ],
    outcomes: [
      "Build responsive websites using HTML, CSS, and JavaScript",
      "Implement modern design principles",
      "Debug and troubleshoot web applications",
      "Deploy websites to hosting platforms",
    ],
  },
  "js-frameworks": {
    title: "JavaScript Frameworks",
    code: "WD201",
    description:
      "Master popular JavaScript frameworks including React, Vue, and Angular to build dynamic and interactive web applications with modern architecture patterns.",
    instructor: "Prof. Aravind Raj",
    duration: "14 Weeks",
    level: "Intermediate",
    fee: "$699",
    schedule: "Tue, Thu (1:00 PM - 4:00 PM)",
    prerequisites: "Web Development Fundamentals or equivalent experience",
    syllabus: [
      "Week 1-2: Modern JavaScript (ES6+)",
      "Week 3-5: React Fundamentals",
      "Week 6-7: State Management in React",
      "Week 8-9: Vue.js Fundamentals",
      "Week 10-11: Angular Basics",
      "Week 12-14: Framework Comparison Project",
    ],
    outcomes: [
      "Build single-page applications using React, Vue, and Angular",
      "Implement state management solutions",
      "Create reusable components and modules",
      "Understand the strengths and weaknesses of each framework",
    ],
  },
  "python-basics": {
    title: "Python Programming",
    code: "PY101",
    description:
      "Learn Python syntax, data structures, and programming concepts for various applications including automation, data analysis, and web development.",
    instructor: "Dr. Deepak Kumar",
    duration: "10 Weeks",
    level: "Beginner",
    fee: "$449",
    schedule: "Mon, Wed (6:00 PM - 8:00 PM)",
    prerequisites: "None",
    syllabus: [
      "Week 1-2: Python Syntax and Data Types",
      "Week 3-4: Control Flow and Functions",
      "Week 5-6: Data Structures and File Handling",
      "Week 7-8: Object-Oriented Programming",
      "Week 9-10: Practical Applications and Final Project",
    ],
    outcomes: [
      "Write efficient Python code for various applications",
      "Implement data structures and algorithms",
      "Create automated scripts for repetitive tasks",
      "Build simple applications with Python",
    ],
  },
  "data-science": {
    title: "Data Science & Analytics",
    code: "DS201",
    description:
      "Master data analysis, visualization, and machine learning techniques with Python. Learn to extract insights from data and build predictive models.",
    instructor: "Dr. Kavitha Devi",
    duration: "16 Weeks",
    level: "Intermediate",
    fee: "$799",
    schedule: "Tue, Thu (2:00 PM - 5:00 PM)",
    prerequisites: "Python Programming or equivalent experience",
    syllabus: [
      "Week 1-2: Data Analysis with NumPy and Pandas",
      "Week 3-4: Data Visualization with Matplotlib and Seaborn",
      "Week 5-6: Statistical Analysis",
      "Week 7-9: Machine Learning Fundamentals",
      "Week 10-12: Supervised and Unsupervised Learning",
      "Week 13-14: Natural Language Processing",
      "Week 15-16: Capstone Project",
    ],
    outcomes: [
      "Analyze and visualize complex datasets",
      "Build and evaluate machine learning models",
      "Extract insights from data to support decision-making",
      "Implement end-to-end data science projects",
    ],
  },
  cybersecurity: {
    title: "Cybersecurity",
    code: "CS301",
    description:
      "Develop skills to protect systems and networks from digital attacks and security breaches. Learn ethical hacking, threat detection, and security best practices.",
    instructor: "Senthil Kumar",
    duration: "14 Weeks",
    level: "Advanced",
    fee: "$899",
    schedule: "Mon, Wed, Fri (2:00 PM - 4:00 PM)",
    prerequisites: "Networking Fundamentals or equivalent experience",
    syllabus: [
      "Week 1-2: Cybersecurity Fundamentals",
      "Week 3-4: Network Security",
      "Week 5-6: Ethical Hacking",
      "Week 7-8: Vulnerability Assessment",
      "Week 9-10: Security Operations",
      "Week 11-12: Incident Response",
      "Week 13-14: Security Certification Preparation",
    ],
    outcomes: [
      "Identify and mitigate security vulnerabilities",
      "Implement security best practices",
      "Respond to security incidents effectively",
      "Prepare for industry-standard security certifications",
    ],
  },
  "mobile-dev": {
    title: "Mobile App Development",
    code: "MD201",
    description:
      "Learn to build native and cross-platform mobile applications for iOS and Android using modern frameworks and tools.",
    instructor: "Anitha Ramesh",
    duration: "15 Weeks",
    level: "Intermediate",
    fee: "$749",
    schedule: "Tue, Thu (10:00 AM - 1:00 PM)",
    prerequisites: "Web Development Fundamentals or equivalent experience",
    syllabus: [
      "Week 1-3: Mobile Development Fundamentals",
      "Week 4-6: React Native Basics",
      "Week 7-9: State Management and API Integration",
      "Week 10-12: Native Features (Camera, GPS, etc.)",
      "Week 13-15: App Store Deployment and Final Project",
    ],
    outcomes: [
      "Build cross-platform mobile applications",
      "Implement native device features",
      "Design responsive mobile interfaces",
      "Deploy applications to app stores",
    ],
  },
}

